# Header
navbar_brand: false
menu:
  Home: index.html
  Archives: archives/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
widgets:
- about         # See also: `about_content`
- category
- tag
- tagcloud
- archive
- recent_posts
about_widget_content: >
  <p>よわよわC++er, Android(カスタムROM), mirmidivi developer</p>
  <p>Twitter:
  <a href="https://twitter.com/shunonymous">@shunonymous</a>
  Mastodon(pawoo):
  <a href="https://pawoo.net/@shunonymous">@shunonymous@pawoo.net</a>
  GitHub:
  <a href="https://github.com/shunonymous">shunonymous</a>
  GitLab(mirror):
  <a href="https://gitlab.com/shunonymous">shunonymous</a>
  </p>

  <p>License:</p>
  Except where otherwise noted, this website is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International</a>
  (All example codes are licensed under <a rel="license" href="https://creativecommons.org/publicdomain/zero/1.0/">CC0 1.0 Universal</a>)
  

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon:
twitter_id: shunonymous
google_plus:
fb_admins:
fb_app_id:
